### ISSUE TITLE
Using self.async_update_ha_state() without enabling force_update

### ISSUE THREAD

**Issue by tetele** [ScratMan/HASmartThermostat#155] opened 2023-05-25 08:24 UTC
**Describe the bug**
I get the following error log message for each `climate` entity:

```
Entity climate.office_floor_heating (<class 'custom_components.smart_thermostat.climate.SmartThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
```

**To Reproduce**
1. Start HA with at least one SmartThermostat component configured
2. Go to Logs
3. Notice the error

**Expected behavior**
No error message, obviously :)

**Screenshots**

**HA instance:**
 - OS: HAOS 10.1
 - HA version: 2023.5.4
 - SmartThermostat Component Version 2023.2.1

**Additional context**

**Comment by alexh3o** [comment] 2023-05-25 09:56
Same issue for me on HA Supervised and everything up to date.

**Comment by ScratMan** [comment] 2023-05-25 11:43
Duplicate of #149

**Closed by ScratMan** 2023-05-25 11:43 UTC
